### ISSUE TITLE
column headers mangled after row delete

### ISSUE THREAD

**Issue by kathrynlmclark** [jspreadsheet/ce#130]
love the plugin.  having difficulty with nested column headers on row delete action.  here's the code as well as before and after images.  its possible there is a better way to handle multiple row headers and that may be part of the problem.  advise appreciated.

```
var testdata = [
['BR', 'Cheese', 1, 3.99],
['CA', 'Apples', 0, 1.00],
['US', 'Carrots', 1, 0.90],
['GB', 'Oranges', 0, 1.20],
['CH', 'Chocolats', 1, 0.40],
['AR', 'Apples', 1, 1.10],
['AR', 'Bananas', 1, 0.30],
['BR', 'Oranges', 1, 0.95],
['BR', 'Pears', 1, 0.90],
['BR', 'Oranges', 1, 0.95],
['BR', 'Pears', 1, 0.90],
['BR', 'Oranges', 1, 0.95],
['BR', 'Pears', 1, 0.90],
];

$('#idMutiPartsGrid').jexcel({
    data: testdata,
    colHeaders: ['Part Number', 'Part Description', 'Escalation Index', 'Purchase Order #', "Quantity", "Delivery  Date (Midpoint)", "Price ($/Unit)","Quantity", "Delivery  Date (Midpoint)", "Price ($/Unit)", "Non-Recurring (Total $)", "Total $", "Analysis Pric"],
    colWidths: [80, 90, 80, 80, 60, 70, 50, 50, 70, 50,60, 60, 80],
    columns: [
        {type: 'autocomplete', url: '/reports/parts/ajax'},
        {type: 'readonly'},
        {type: 'text'},
        {type: 'text'},
    ],
    tableOverflow: true,
    tableHeight: '350px'
});

setTimeout(function (){
    $('#idMutiPartsGrid').find('thead').before('<thead class="jexcel_label"><tr><td class="jexcel_label" width="30"></td><td colspan="3" width="250" ></td><td colspan="4" width="260" align="center">PRIOR  PURCHASE</td><td  colspan="5"  width="290" align="center">PROPOSED</td></tr></thead>');
},1000);
```

before
![before-row-delete](https://user-images.githubusercontent.com/24375939/39254280-bc66d422-4877-11e8-9eb0-9caae746a7c8.png)

after
![after-row-delete](https://user-images.githubusercontent.com/24375939/39254291-c10f2402-4877-11e8-84d2-cba7183b8e3c.png)

**Comment by lironka** [comment]
Why did you break the table? Why your table has in first header 13 columns (1 + 3 + 4 + 5 )  but second  header has 14 columns? 
Add 1 column to the first header, may be it helps you.

**Comment by pphod** [comment]
You need to recreate you thead after delete the column. You should do that
using the event: ondeletecolumn : function() { recreate your thead }

**Comment by kathrynlmclark** [comment]
@lironka because deleting the row made a duplicate quantity column somehow.
@paulhodel thanks for getting back so soon - this was on row delete not column delete.  does your comment still apply?

**Comment by pphod** [comment]
Yes, you should that... we are working on a native feature to handle that better. Should be ready in the next release.

**Comment by pphod** [comment]
This has been fixed in the latest version in the master repository.

**Comment by morgunder** [comment]
@paulhodel thank you.

**Comment by morgunder** [comment]
@paulhodel still seeing the headers not aligned.  any tricks to try?
![screen shot 2018-06-01 at 3 36 55 pm](https://user-images.githubusercontent.com/3998336/40860087-07d216f4-65b2-11e8-9ae6-d06c591608a0.png)
