### ISSUE TITLE
v3 Context Menu Always Pops Up On Left Side Of Worksheet

### ISSUE THREAD

**Issue by PRISMAY** [jspreadsheet/ce#394]
Note where the context menu always pops up in the configuration used in this [jsFiddle](https://jsfiddle.net/AYSabre/8szpqyta/).  Not sure what setting is breaking this right now.

**Comment by coreysherman** [comment]
I am experiencing this exact same issue.  I'm glad that you posted a fiddle, even with removing all your CSS, the problem persists, so I don't think it's necessarily conflicting CSS...

**Comment by PRISMAY** [comment]
I updated the fiddle to use a simple set up too from the jexcel examples and it still does the same thing.

**Comment by coreysherman** [comment]
The same thing happens even when you remove everything but the data... Surely this is just broken in this release? Or are we missing settings that should be applied when creating an instance of jexcel?

**Comment by PRISMAY** [comment]
I think it's how it's hosted and how the location for the context menu is determined.  Had no issue with jexcel v2.  We host the worksheet in an overlay/dialog instead of a main page. I'm sure jsFiddle is just duplicating our overlay/dialog environment which is helpful and can hopefully bring a resolution to this issue sooner than later.

**Comment by coreysherman** [comment]
You might be on to something. I just created a raw html file with nothing on it at all except the minimum jexcel needs to function and the context menu works properly.

We're not putting ours inside anything overly complicated, but it is nested a bit.  Maybe there is another library from jFiddle that you and I are using that's conflicting somehow? I'd imagine it has to do with capturing the x, y coordinates from the mouse event...

**Comment by pphod** [comment]
Quick fix: remove `<!DOCTYPE html>` and leave `<html>` only in your HTML template file.

I am working on a patch will be available soon.

**Comment by pphod** [comment]
This has been fixed. jApp.js and jApp.css has been included in the master repository and the npm v3.0.4+

**Comment by PRISMAY** [comment]
Thank you.

**Comment by coreysherman** [comment]
For me, this is closer, but still not offset correctly.  It is now honoring the x coordinate from the click, but the y coordinate is still too low.  

![In this screenshow, the selected cell is the one I right clicked on.](https://user-images.githubusercontent.com/45212492/60052160-92023f80-96a2-11e9-8923-cbc2a817b260.png)

**Comment by pphod** [comment]
Should be fixed now. It was due jExcel instances inside position:relative parents...

**Comment by coreysherman** [comment]
That did it for me, thank you so much!
