### ISSUE TITLE
problem using other language

### ISSUE THREAD

**Issue by rsauto9311** [jspreadsheet/ce#563]
https://github.com/handsontable/handsontable/issues/839

For example, I wanna write "한글", but the cell present "gㅏㄴ글".
"아이" -> "dㅏ이".
"도시" -> "eㅗ시".

**Comment by pphod** [comment]
It has been fixed in the master repository

**Comment by shojibur** [comment]
@pphod Not sure, i am still getting same error. using latest version

**Comment by hodeware** [comment]
The 100% MEI friendly is only avaliable on the Pro version.
https://jspreadsheet.com
