### ISSUE TITLE
Copy paste multiple cell

### ISSUE THREAD

**Issue by ponyEdp** [jspreadsheet/ce#591]
Good morning 
If I copy one cell and I paste in multiple cells (for example 10 cells), it will paste only in one cell.
May you fix ?
I use ctrl + C to copy and ctrl + V to paste.
Regards

**Comment by giko45** [comment]
fixed in #594

**Comment by nsreyes** [comment]
Hi, It seems that pull request #594 was never been merged.

**Comment by pearcemichal** [comment]
Has there been any update on this? as far as I can tell this is still not working in the latest version / latest source.
