### ISSUE TITLE
sorting broken in v4?

### ISSUE THREAD

**Issue by gshklover** [jspreadsheet/ce#963]
Sorting seems to be broken in v4 but works in v3?
From examples documentation (v4 shows sorting button but does not sort the content):
<html>
	<head>
	<html>
	
		<script src="https://bossanova.uk/jexcel/v3/jexcel.js"></script>
		<script src="https://bossanova.uk/jsuites/v2/jsuites.js"></script>
		<link rel="stylesheet" href="https://bossanova.uk/jexcel/v3/jexcel.css" type="text/css" />
		<link rel="stylesheet" href="https://bossanova.uk/jsuites/v2/jsuites.css" type="text/css" />
	
	</head>
<body>
<div id="abc"></div>
<script>
   var data = [
    ['Jazz', 'Honda', '2019-02-12', 10],
    ['Civic', 'Honda', '2018-07-11', 20],
   ];

  jexcel(document.getElementById('abc'), {
    data: data,
    columns: [{type: 'text'}, {type: 'text'}, {type: 'text'}, {type: 'numeric'}],
	allowInsertRow: false,
	allowDeleteRow: false,
	editable: false
  })
</script>
</body>
</html>

**Comment by sasha-x** [comment]
+1 looks almost completely broken.

**Comment by pphod** [comment]
It will be reviewed during the weekend on the next release.

**Comment by pphod** [comment]
This has been changed on v4.2+

**Comment by pphod** [comment]
It has been fixed on v4.2+

**Comment by cdilga** [comment]
The example is still broken on: https://bossanova.uk/jexcel/v4/
